### ISSUE TITLE
Show 'from', 'to' on result page

### ISSUE THREAD

**Issue by s0ph1e** [s0ph1e/eml-reader#1]
Add next fields:

- [ ] from
- [ ] to
- [ ] date
- [ ] subject

**Comment by wolfpil** [comment]
OK, sorry for my unfriendliness.

Here is a detailed question:

I'm looking inside public/js/app.js, line 50 - 51

      $.ajax({
          // This should be the server script to process the upload
         url: '/read',
         ....

I'm sorry I cannot find the file 'read' in your repo.

**Comment by s0ph1e** [comment]
Hello @wolfpil 

This app contains frontend part - in `public` folder and backed part on nodejs - in `app.js` file. There is no read file because `/read` is handled by backend, in this endpoint https://github.com/s0ph1e/eml-reader/blob/5f4ab4c30e2f2386fcbd31c3d6ead73b960f955f/routes.js#L5

To launch app you need to do next:
* install dependencies with command `npm install` 
* then run nodejs server with next command`node app.js`
* then open [localhost:3000](http://localhost:3000) 

Hope it helps

**Comment by wolfpil** [comment]
Thanks, that helped me out.

It's a relatively easy task to include "From", "To", "CC", "Date" and "Subject" fields from the eml file.

Certainly I will send you my changed and added files if you're interested in.

But now I also want to make the embedded attachments downloadable. And that seems to be a bit more difficult, because the attachments are converted to json. And you will have to store the attachments first in an own directory to make them attainable - as far as I see now.

Do you know how to make the original attachments of the eml files downloadable?

Thanks.

**Comment by s0ph1e** [comment]
Hey @wolfpil  
it would be great if you can open PR with your changes for `to`, `from` etc.

As for attachments - I believe it is not necessary to save attachments to file system. As they are returned in ajax response - we can use some module on frontend which allows to save buffer as file. I tried [save-file](https://www.npmjs.com/package/save-file) module - it works perfectly fine (but using it may require to add webpack to build frontend). But maybe there is some jquery plugin or pure js functionality which can do this

**Comment by s0ph1e** [comment]
Hi @wolfpil, FYI I've added attachments download
